### ISSUE TITLE
l1, l2 tile sizes are not guaranteed to evenly divide the matrix, is there a fix?

### ISSUE THREAD

**Issue by yunchenlo** [EECS-NTNU/bismo#2] opened 2019-03-04 13:36 UTC
In your source code bismo/src/main/cpp/app/BitSerialMatMulExecutor.hpp
I found that when the matrix size is too big (e.g. 1024x4096x1), the results of the matrix multiplication will be wrong. Or even cannot pass the assertion. Did you guys find a way to ensure BISMO can support any size of the matrix even if the size is bigger? 

Many Thanks,
Yun-Chen Lo
================= The comment I found in code is listed as below
// TODO l1 tile size is not guaranteed to evenly divide the matrix
// due to partial tiles, and same with l2 tile size. need to handle this
// either by smart padding/alignment during allocation, or changing tile
// upper bounds.

**Comment by maltanar** [comment] 2019-03-04 15:17
Hi Yun-Chen,

This BISMO release was intended to demo the hardware only, large parts of the software stack are still missing. The included driver is only there as a small example of what could be done.

In principle there is no limitation to the matrix size, since we can move data from DRAM to the on-chip buffers and the rows/columns/.. can be made divisible by the hardware tile size by adding zero padding, and adding the appropriate loop tiling for instruction generation. However we don't have this at the moment.

**Comment by yunchenlo** [comment] 2019-03-05 05:32
Dear @maltanar,

I see. Thank you!
However because I need a workable version of drivers for bismo to run any size of mmul in order to do some experiments. Where do you suggest to add zero padding & loop tiling code?

Thanks,
Yun-Chen Lo

**Comment by maltanar** [comment] 2019-03-06 22:01
The zero padding is actually already handled inside the allocGEMMContext function [here](https://github.com/EECS-NTNU/bismo/blob/master/src/main/cpp/app/BitSerialMatMulAccelDriver.hpp#L142) - BISMO uses the gemmbitserial library to store bit-serial matrices, and gemmbitserial internally supports zero-padding columns and rows so that they are aligned to desired sizes. For loop tiling, I'd use the [build_schedule_trivial](https://github.com/EECS-NTNU/bismo/blob/master/src/main/cpp/app/BitSerialMatMulExecutor.hpp#L544) in BitSerialMatMulExecutor as a starting point, seeing that there already is some loop tiling there.

**Comment by maltanar** [comment] 2019-11-12 15:07
I'm closing this issue since this should no longer be an issue in the new version (i.e. the release in June'19) of BISMO.

**Closed as completed by maltanar** 2019-11-12 15:07 UTC
